version: '3'
services:
  nodejs-server:
    build:
      context: ./docker_build
    ports:
      - "8080:8080"
    container_name: vvly-frontend-vue
    volumes:
      - ./:/usr/src/app
    tty: true
